# Generated by Django 5.0.8 on 2024-08-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_daily_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
