# Generated by Django 5.0.8 on 2024-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_image_delete_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='car_images/hero.png', upload_to='car_images/'),
        ),
    ]
