# Generated by Django 5.0.8 on 2024-09-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dbrbetq4s/image/upload/v1726855701/images/car_images/hero_gybvzv.png', upload_to='car_images/'),
        ),
    ]
