# Generated by Django 5.0.8 on 2024-09-21 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbrbetq4s/image/upload/v1726855701/images/car_images/hero_gybvzv.png', max_length=255, verbose_name='image'),
        ),
    ]
