# Generated by Django 5.0.8 on 2024-09-21 05:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/car_images/hero_gybvzv.png', max_length=255, verbose_name='image'),
        ),
    ]
