# Generated by Django 5.0.8 on 2024-12-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/car_images/hero.png', upload_to='images'),
        ),
    ]
